platform :ios, '11.0'

#TODO: create podspec repo or add to mobile-ios-podspecs
#source 'git@github.com:surveysampling/mobile-ios-podspecs'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'PeanutLabs-iOS_Example' do
  pod 'PeanutLabs-iOS', :path => '../'

  target 'PeanutLabs-iOS_Tests' do
    inherit! :search_paths
    
  end
end
